---
driver:
  name: proxy
  host: localhost

transport:
  port: 22
  username: travis
  password: travis

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

provisioner:
  name: salt_solo
  log_level: quiet
  require_chef: false
  formula: ulog
  state_top:
    base:
      '*':
        - ulog

suites:
  - name: ulogd2
    provisioner:
      pillars-from-files:
        ulog.sls: pillar.example
      pillars:
        top.sls:
          base:
            '*':
              - ulog
