sudo: required
language: python
cache: bundler
services:
  - docker

before_install:
  - bundle install

env:
  matrix:
    - INSTANCE: ulogd2-ubuntu-1404
    - INSTANCE: ulogd2-ubuntu-1604

script:
  - bundle exec kitchen verify ${INSTANCE}
